sudo: false
language: go
go:
  - "1.13.x"
env:
  - GO111MODULE=on
nstall:
  - go get -u golang.org/x/lint/golint
script:
  - go build -o kubectl-sql cmd/kubectl-sql/*.go
  - golint ./pkg/... & golint ./cmd/...
  - test -s $(go fmt ./cmd/... ./pkg/...) 
