apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: sql
spec:
  version: v0.2.11
  homepage: https://github.com/yaacov/kubectl-sql
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/yaacov/kubectl-sql/releases/download/v0.2.11/kubectl-sql.tar.gz
    sha256: 831f5fab3e6b8ece5ca5659bb803c88065c0487427bba793becf8e2b6bd00f8a
    files:
    - from: "*"
      to: "."
    bin: kubectl-sql
  shortDescription: Use SQL like language to query the Kubernetes cluster manager.
  description: |
    This plugin use SQL like language to query the Kubernetes cluster manager.
  caveats: |
    Usage:
      $ kubectl sql
    For additional options:
      $ kubectl sql --help
      or https://github.com/yaacov/kubectl-sql
