name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build and package
        run: |
          make
          make dist
        env:
          VERSION: ${{ github.event.release.tag_name }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./kubectl-sql.tar.gz
          asset_name: kubectl-sql.tar.gz
          asset_content_type: application/gzip

      - name: Upload Checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./kubectl-sql.tar.gz.sha256sum
          asset_name: kubectl-sql.tar.gz.sha256sum
          asset_content_type: text/plain
